# Generated by Django 5.2.7 on 2025-10-25 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moraleja_sugerida', models.CharField(max_length=255)),
                ('razon_sugerencia', models.TextField(help_text='Por qué se sugirió')),
                ('valores_cubiertos', models.JSONField(default=list)),
                ('fue_seleccionada', models.BooleanField(default=False)),
                ('video_generado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción con Sugerencia',
                'verbose_name_plural': 'Interacciones con Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_nino', models.IntegerField(default=7, help_text='Edad del niño (5-10 años)')),
                ('nivel_complejidad', models.CharField(choices=[('simple', 'Simple (5-6 años)'), ('medio', 'Medio (7-8 años)'), ('avanzado', 'Avanzado (9-10 años)')], default='medio', max_length=20)),
                ('estilo_narrativo', models.CharField(choices=[('aventurero', 'Aventurero (acción y descubrimientos)'), ('educativo', 'Educativo (didáctico y explicativo)'), ('fantastico', 'Fantástico (mágico e imaginativo)')], default='aventurero', max_length=50)),
                ('temas_favoritos', models.JSONField(default=list, help_text="Lista de temas: ['animales', 'aventura', 'ciencia']")),
                ('valores_prioritarios', models.JSONField(default=list, help_text="Lista de valores: ['empatía', 'honestidad', 'responsabilidad']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
