# Generated by Django 5.2.7 on 2025-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='edad_nino',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estilo_narrativo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nivel_complejidad',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='temas_favoritos',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='valores_prioritarios',
            field=models.JSONField(default=list, help_text="Lista de valores educativos: ['empatía', 'honestidad', 'responsabilidad']"),
        ),
    ]
